<img src=""/>

Exercise: Dictionaries
======================

Problems for exercise and homework for the [Python Fundamentals Course
@SoftUni](https://softuni.bg/trainings/2442/python-fundamentals-september-2019).
Submit your solutions in the SoftUni judge system at
<https://judge.softuni.bg/Contests/1737>

1.Count Chars in a String
==
-----------------------

Write a program that **counts all characters** in a string **except for
space (' ')**.

**Print all the occurrences in the following format:**

**{char} -\> {occurrences}**

### Examples

<table>
<thead>
<tr class="header">
<th><strong>Input</strong></th>
<th><strong>Output</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>text</strong></td>
<td><p>t -&gt; 2</p>
<p>e -&gt; 1</p>
<p>x -&gt; 1</p></td>
</tr>
<tr class="even">
<td><strong>text text text</strong></td>
<td><p>t -&gt; 6</p>
<p>e -&gt; 3</p>
<p>x -&gt; 3</p></td>
</tr>
</tbody>
</table>

In [ ]:
text_string = "".join(input().split(" "))

count_chars_dict = {}

for char in text_string:
    if char in count_chars_dict:
        continue
    else:
        count_chars_dict[char] = text_string.count(char)

for key, value in count_chars_dict.items():
    print(f'{key} -> {value}')

2.A Miner Task
==
------------

You will be given a sequence of strings, each on a new line. Every odd
line on the console is representing a resource (e.g. Gold, Silver,
Copper, and so on) and every even – quantity. Your task is to collect
the resources and print them each on a new line.

**Print the resources and their quantities in the following format:**

**{resource} –\> {quantity}**

The quantities will be **in the range** **\[1 … 2 000 000 000\]**

### Examples

<table>
<thead>
<tr class="header">
<th><strong>Input</strong></th>
<th><strong>Output</strong></th>
<th></th>
<th><strong>Input</strong></th>
<th><strong>Output</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">

<td><p>Gold<br>155<br>Silver<br>10<br>Copper<br>17<br>stop</p></td>

<td><p>Gold -&gt; 155</p>
<p>Silver -&gt; 10</p>
<p>Copper -&gt; 17</p></td>
<td></td>

<td><p>gold<br>155<br>silver<br>10<br>copper<br>17<br>gold<br>15<br>stop</p></td>

<td><p>gold -&gt; 170</p>
<p>silver -&gt; 10</p>
<p>copper -&gt; 17</p></td>
</tr>
</tbody>
</table>

In [ ]:
metals_dict = {}

while True:
    str_input = input()
    if str_input == "stop":
        break
    else:
        int_input = int(input())

    if str_input in metals_dict:
        metals_dict[str_input] += int_input
    else:
        metals_dict[str_input] = int_input

for resource, quantity in metals_dict.items():
    print(f'{resource} -> {quantity}')

3.Legendary Farming
==
-----------------

You've done all the work and the last thing left to accomplish is to own
a **legendary item**. However, it's a tedious process and it requires
quite a bit of farming. Anyway, you are not too pretentious – any
legendary item will do. The possible **items** are:

-   **Shadowmourne** – requires **250 Shards**;

-   **Valanyr** – requires **250 Fragments**;

-   **Dragonwrath** – requires **250 Motes**;

**Shards, Fragments** and **Motes** are the **key materials** and
everything else is **junk.** You will be given lines of input, in the
format:

**2 motes 3 ores 15 stones**

Keep track of the **key materials -** the **first** one that reaches the
**250 mark,** **wins** the **race**. At that point you have to print
that the corresponding legendary item is obtained. Then, print the
**remaining** shards, fragments, motes, ordered by **quantity** in
**descending** order, then by **name** in **ascending** order, each on a
new line. Finally, print the collected **junk** items in
**alphabetical** order.

### Input

-   Each line comes in the following format: **{quantity} {material}
    > {quantity} {material} … {quantity} {material}**

### Output

-   On the first line, print the obtained item in the format:
    **{Legendary item} obtained!**

-   On the next three lines, print the remaining key materials in
    **descending order by quantity**

    -   If **two** key materials have the same quantity, print them in
        **alphabetical** **order**

-   On the final several lines, print the **junk** items **in
    alphabetical order**

    -   All materials are printed in format **{material}: {quantity}**

    -   The output should be **lowercase**, except for the first letter
        of the legendary

### Examples

<table>
<thead>
<tr class="header">
<th><strong>Input</strong></th>
<th><strong>Output</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">

<td><p>3 Motes 5 stones 5 Shards<br>6 leathers 255 fragments 7 Shards</p></td>

<td><p>Valanyr obtained!</p>
<p>fragments: 5</p>
<p>shards: 5</p>
<p>motes: 3</p>
<p>leathers: 6</p>
<p>stones: 5</p></td>
</tr>
<tr class="even">

<td><p>123 silver 6 shards 8 shards 5 motes<br>9 fangs 75 motes 103 MOTES 8 Shards<br>86 Motes 7 stones 19 silver</p></td>

<td><p>Dragonwrath obtained!</p>
<p>shards: 22</p>
<p>motes: 19</p>
<p>fragments: 0</p>
<p>fangs: 9</p>
<p>silver: 123</p></td>
</tr>
</tbody>
</table>

In [ ]:
legendary_recipes = {'shards': 'Shadowmourne', 'fragments': 'Valanyr', 'motes': 'Dragonwrath'}
key_materials = {'shards': 0, 'fragments': 0, 'motes': 0}
do_i_get_legendary_item = False
junk = {}

while True:
    if do_i_get_legendary_item:
        break
    else:
        user_input = input().lower().split(" ")
        for index in range(0, len(user_input), 2):
            user_input[index + 1] = user_input[index + 1]
            if user_input[index + 1] in key_materials:
                key_materials[user_input[index + 1]] += int(user_input[index])
                if key_materials[user_input[index + 1]] >= 250:
                    print(f"{legendary_recipes[user_input[index + 1]]} obtained!")
                    key_materials[user_input[index + 1]] = key_materials[user_input[index + 1]] - 250
                    do_i_get_legendary_item = True
                    break
            else:
                if user_input[index + 1] in junk:
                    junk[user_input[index + 1]] += int(user_input[index])
                else:
                    junk[user_input[index + 1]] = int(user_input[index])

for i in sorted(sorted(key_materials), key=lambda x: key_materials[x], reverse=True):
    print(f"{i}: {key_materials[i]}")

for i in sorted(junk):
    print(f"{i}: {junk[i]}")

4.Orders
==
------

Write a program that keeps information about **products** and their
**prices**. Each product has a **name**, a **price** and a **quantity**.
If the product **doesn't exist** yet, **add** it with its **starting
quantity**.

If you receive a product, which **already exists,** **increase** its
quantity by the input quantity and if its **price** is different,
**replace** the price as well.

You will receive products' **names**, **prices** and **quantities** on
**new lines**. Until you receive the command "**buy**", keep adding
items. When you do receive the command "**buy**", print the items with
their **names** and **total price** of all the products with that name.

**Input**

-   Until you receive "**buy**", the products will be coming in the
    format: "**{name} {price} {quantity}**".

-   The product data is **always** delimited by a **single space**.

**Output**

-   Print information about **each** **product** in the following
    format:  
    **"{productName} -\> {totalPrice}"**

-   **Format** the average grade to the **2<sup>nd</sup> digit after the
    decimal separator**.

### Examples

<table>
<thead>
<tr class="header">
<th><strong>Input</strong></th>
<th><strong>Output</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">

<td><p>Beer 2.20 100<br>IceTea 1.50 50<br>NukaCola 3.30 80<br>Water 1.00 500<br>buy</p></td>

<td><p>Beer -&gt; 220.00</p>
<p>IceTea -&gt; 75.00</p>
<p>NukaCola -&gt; 264.00</p>
<p>Water -&gt; 500.00</p></td>
</tr>
<tr class="even">

<td><p><strong>Beer 2.40 350</strong><br><strong>Water 1.25 200</strong><br><strong>IceTea 5.20 100</strong><br><strong>Beer 1.20 200</strong><br><strong>IceTea 0.50 120</strong><br>buy</p></td>

<td><p>Beer -&gt; 660.00</p>
<p>Water -&gt; 250.00</p>
<p>IceTea -&gt; 110.00</p></td>
</tr>
<tr class="odd">

<td><p>CesarSalad 10.20 25<br>SuperEnergy 0.80 400<br>Beer 1.35 350<br>IceCream 1.50 25<br>buy</p></td>

<td><p>CesarSalad -&gt; 255.00</p>
<p>SuperEnergy -&gt; 320.00</p>
<p>Beer -&gt; 472.50</p>
<p>IceCream -&gt; 37.50</p></td>
</tr>
</tbody>
</table>

In [ ]:
items_list = []
items_dict = {}

while True:
    user_input = input()
    if user_input == 'buy':
        break
    else:
        user_input = user_input.split(" ")
        quantity = int(user_input[2])
    if user_input[0] not in items_list:
        items_list.append(user_input[0])
        items_dict[user_input[0]] = [float(user_input[1]), quantity]
    else:
        old_quantity = items_dict[user_input[0]][1]
        items_dict[user_input[0]] = [float(user_input[1]), quantity + old_quantity]

for i in items_list:
    print(f"{i} -> {items_dict[i][0] * items_dict[i][1]:.2f}")

5.SoftUni Parking
==
---------------

SoftUni just got a new **parking lot**. It's so fancy, it even has
online **parking validation**. Except the online service doesn't work.
It can only receive users' data, but it doesn't know what to do with it.
Good thing you're on the dev team and know how to fix it, right?

Write a program, which validates a parking place for an online service.
Users can **register** to park and **unregister** to leave.

The program **receives 2 types of commands**:

-   "**register {username} {licensePlateNumber}**":

    -   The system only supports **one car per user** at the moment, so
        if a user tries to register **another license plate**, using the
        **same username**, the system should print:  
        "**ERROR: already registered with plate number
        {licensePlateNumber}**"

    -   If the aforementioned checks passes successfully, the plate can
        be registered, so the system should print:  
        **"{****username} registered {licensePlateNumber}
        successfully"**

-   "**unregister {username}**":

    -   If the user is **not present** in the database, the system
        should print:  
        "**ERROR: user {username} not found**"

    -   If the aforementioned check passes successfully, the system
        should print:  
        "**{username} unregistered successfully**"

After you execute all of the commands, **print** all the currently
**registered users** and their **license plates** in the format:

-   "**{username} =\> {licensePlateNumber}**"

### Input

-   First line: **n** – **number of commands** – **integer**

-   Next **n** lines: **commands** in one of the **two** possible
    formats:

    -   Register: "**register {username} {licensePlateNumber}**"

    -   Unregister: "**unregister {username}**"

The input will **always** be **valid** and you **do not need** to check
it explicitly.

### Examples

<table>
<thead>
<tr class="header">
<th><strong>Input</strong></th>
<th><strong>Output</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">

<td><p>5<br>register John CS1234JS<br>register George JAVA123S<br>register Andy AB4142CD<br>register Jesica VR1223EE<br>unregister Andy</p></td>

<td><p>John registered CS1234JS successfully</p>
<p>George registered JAVA123S successfully</p>
<p>Andy registered AB4142CD successfully</p>
<p>Jesica registered VR1223EE successfully</p>
<p>Andy unregistered successfully</p>
<p>John =&gt; CS1234JS</p>
<p>George =&gt; JAVA123S</p>
<p>Jesica =&gt; VR1223EE</p></td>
</tr>
<tr class="even">

<td><p><strong>4</strong><br><strong>register Jony AA4132BB</strong><br><strong>register Jony AA4132BB</strong><br><strong>register Linda AA9999BB</strong><br><strong>unregister Jony</strong></p></td>

<td><p><strong>Jony registered AA4132BB successfully</strong></p>
<p><strong>ERROR: already registered with plate number AA4132BB</strong></p>
<p><strong>Linda registered AA9999BB successfully</strong></p>
<p><strong>Jony unregistered successfully</strong></p>
<p><strong>Linda =&gt; AA9999BB</strong></p></td>
</tr>
<tr class="odd">

<td><p>6<br>register Jacob MM1111XX<br>register Anthony AB1111XX<br>unregister Jacob<br>register Joshua DD1111XX<br>unregister Lily<br>register Samantha <strong>AA9999BB</strong></p></td>

<td><p>Jacob registered MM1111XX successfully</p>
<p>Anthony registered AB1111XX successfully</p>
<p>Jacob unregistered successfully</p>
<p>Joshua registered DD1111XX successfully</p>
<p>ERROR: user Lily not found</p>
<p>Samantha registered AA9999BB successfully</p>
<p>Anthony =&gt; AB1111XX</p>
<p>Joshua =&gt; DD1111XX</p>
<p>Samantha =&gt; AA9999BB</p></td>
</tr>
</tbody>
</table>

In [ ]:
visitors = {}
regs = int(input())

for i in range(regs):
    entry = input().split()
    command = entry[0]
    person = entry[1]
    if command == 'register':
        if person in visitors:
            print(f"ERROR: already registered with plate number {visitors[person]}")
        else:
            visitors[person] = entry[2]
            print(f"{person} registered {visitors[person]} successfully")
    if command == 'unregister':
        if person in visitors:
            print(f"{person} unregistered successfully")
            del visitors[person]
        else:
            print(f"ERROR: user {person} not found")

for visitor in visitors:
    print(f"{visitor} => {visitors[visitor]}")

6.Courses
==
-------

Write a program that keeps information about **courses**. Each course
has a name and registered students.

You will be receiving a **course** **name** and a **student** **name,**
until you receive the command "**end**". **Check if such course already
exists, and if not, add the course.** Register the user into the course.
When you receive the command "**end**", print the courses with their
**names** and **total registered users**, ordered by the count of
registered users in descending order. For each contest print the
registered users **ordered by name** **in ascending order**.

**Input**

-   Until the "**end**" command is received, you will be receiving input
    in the format: "**{courseName} : {studentName}**".

-   The product data is **always** delimited by **" : ".**

**Output**

-   Print the information about **each** **course** in the following the
    format:  
    **"{courseName}: {registeredStudents}"**

-   Print the information about each student, in the following the
    format:  
    **"-- {studentName}"**

### Examples

<table>
<thead>
<tr class="header">
<th><strong>Input</strong></th>
<th><strong>Output</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">

<td><p>Programming Fundamentals : John Smith<br>Programming Fundamentals : Linda Johnson<br>JS Core : Will Wilson<br>Java Advanced : Harrison White<br>end</p></td>

<td><p>Programming Fundamentals: 2</p>
<p>-- John Smith</p>
<p>-- Linda Johnson</p>
<p>JS Core: 1</p>
<p>-- Will Wilson</p>
<p>Java Advanced: 1</p>
<p>-- Harrison White</p></td>
</tr>
<tr class="even">

<td><p><strong>Algorithms : Jay Moore</strong><br><strong>Programming Basics : Martin Taylor</strong><br><strong>Python Fundamentals : John Anderson</strong><br><strong>Python Fundamentals : Andrew Robinson</strong><br><strong>Algorithms : Bob Jackson</strong><br><strong>Python Fundamentals : Clark Lewis</strong><br><strong>end</strong></p></td>

<td><p><strong>Python Fundamentals: 3</strong></p>
<p><strong>-- Andrew Robinson</strong></p>
<p><strong>-- Clark Lewis</strong></p>
<p><strong>-- John Anderson</strong></p>
<p><strong>Algorithms: 2</strong></p>
<p><strong>-- Bob Jackson</strong></p>
<p><strong>-- Jay Moore</strong></p>
<p><strong>Programming Basics: 1</strong></p>
<p><strong>-- Martin Taylor</strong></p></td>
</tr>
</tbody>
</table>

In [ ]:
# 80/100
# Zero test #1 (Time limit)
# The zero tests are not included in the final result.
# Time used: 0.103 s
# Memory used: 8.86 MB
#
# Zero test #2 (Time limit)
# The zero tests are not included in the final result.
# Time used: 0.103 s
# Memory used: 8.85 MB
#
# Test #2 (Time limit)
# Time used: 0.118 s
# Memory used: 8.85 MB

import collections as c

courses = c.defaultdict(list)
while True:
    command = input()
    if command == 'end':
        break
    command = command.split(' : ')
    courses[command[0]].append(command[1])

for course in sorted(courses, key=lambda x: len(courses[x]), reverse=True):
    print(f"{course}: {len(courses[course])}")
    for name in sorted(courses[course]):
        print(f"-- {name}")

7.Student Academy
==
---------------

Write a program that keeps information about **students** and **their
grades**.

You will receive **n pair of rows**. First you will receive the
**student's name**, after that you will receive his grade. **Check if
the student already exists and if not, add him**. Keep track of all
grades for each student.

When you finish reading the data, keep the students with **average grade
higher than or equal to 4.50**. Order the filtered students by **average
grade in descending order**.

**Print the students and their average grade in the following format:**

**{name} –\> {averageGrade}**

**Format** the average grade to the **2<sup>nd</sup> decimal place**.

### Examples

<table>
<thead>
<tr class="header">
<th><strong>Input</strong></th>
<th><strong>Output</strong></th>
<th></th>
<th><strong>Input</strong></th>
<th><strong>Output</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">

<td><p>5<br>John<br>5.5<br>John<br>4.5<br>Alice<br>6<br>Alice<br>3<br>George<br>5</p></td>

<td><p>John -&gt; 5.00</p>
<p>George -&gt; 5.00</p>
<p>Alice -&gt; 4.50</p></td>
<td></td>

<td><p>5<br>Amanda<br>3.5<br>Amanda<br>4<br>Rob<br>5.5<br>Christian<br>5<br>Robert<br>6</p></td>

<td><p>Robert -&gt; 6.00</p>
<p>Rob -&gt; 5.50</p>
<p>Christian -&gt; 5.00</p></td>
</tr>
</tbody>
</table>

In [ ]:
# v1 - 75/100
# Test #1 (Time limit)
# Time used: 0.181 s
# Memory used: 8.88 MB
#
# Test #2 (Time limit)
# Time used: 0.103 s
# Memory used: 8.88 MB

import collections as c

students = c.defaultdict(list)
entries = int(input())

for i in range(entries):
    student = input()
    grade = float(input())
    students[student].append(grade)

students_temp = {}
for key, value in students.items():
    if sum(value) / len(value) >= 4.5:
        students_temp[key] = value

for i in sorted(students_temp, key=lambda x: sum(students_temp[x]) / len(students_temp[x]), reverse=True):
    print(f"{i} -> {sum(students_temp[i]) / len(students_temp[i]):.2f}")

In [ ]:
# v2 - 75/100
# Zero test #2 (Time limit)
# The zero tests are not included in the final result.
# Time used: 0.103 s
# Memory used: 8.87 MB
#
# Test #7 (Time limit)
# Time used: 0.103 s
# Memory used: 8.88 MB
#
# Test #8 (Time limit)
# Time used: 0.103 s
# Memory used: 8.88 MB

from collections import defaultdict

students = defaultdict(list)
entries = int(input())

for i in range(entries):
    student = input()
    grade = float(input())
    students[student].append(grade)

students_temp = {}
for key, value in students.items():
    if sum(value) / len(value) >= 4.5:
        students_temp[key] = value

for i in sorted(students_temp, key=lambda x: sum(students_temp[x]) / len(students_temp[x]), reverse=True):
    print(f"{i} -> {sum(students_temp[i]) / len(students_temp[i]):.2f}")

8.Company Users
==
-------------

Write a program that keeps information about companies and their
employees.

You will be receiving a **company** **name** and an **employee's id,**
until you receive the command "**End**" command. Add each employee to
the given company. Keep in mind that a company cannot have two employees
with the same id.

When you finish reading the data, **order the companies by the name in
ascending order**.

Print the company name and each employee's id in the following format:

**{companyName}**

**-- {id1}**

**-- {id2}**

**-- {idN}**

**Input / Constraints**

-   Until you receive the "**End**" command, you will be receiving input
    in the format: "**{companyName} -\> {employeeId}**".

-   The input always will be valid.

### Examples

<table>
<thead>
<tr class="header">
<th><strong>Input</strong></th>
<th><strong>Output</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">

<td><p><strong>SoftUni -&gt; AA12345</strong><br><strong>SoftUni -&gt; BB12345</strong><br><strong>Microsoft -&gt; CC12345</strong><br><strong>HP -&gt; BB12345</strong><br><strong>End</strong></p></td>

<td><p><strong>HP</strong></p>
<p><strong>-- BB12345</strong></p>
<p><strong>Microsoft</strong></p>
<p><strong>-- CC12345</strong></p>
<p><strong>SoftUni</strong></p>
<p><strong>-- AA12345</strong></p>
<p><strong>-- BB12345</strong></p></td>
</tr>
<tr class="even">

<td><p><strong>SoftUni -&gt; AA12345</strong><br><strong>SoftUni -&gt; CC12344</strong><br><strong>Lenovo -&gt; XX23456</strong><br><strong>SoftUni -&gt; AA12345</strong><br><strong>Movement -&gt; DD11111</strong><br><strong>End</strong></p></td>

<td><p><strong>Lenovo</strong></p>
<p><strong>-- XX23456</strong></p>
<p><strong>Movement</strong></p>
<p><strong>-- DD11111</strong></p>
<p><strong>SoftUni</strong></p>
<p><strong>-- AA12345</strong></p>
<p><strong>-- CC12344</strong></p></td>
</tr>
</tbody>
</table>

In [ ]:
companies = {}

while True:
    command = input()
    if command == "End":
        break
    company, employee_id = command.split(" -> ")
    if company not in companies:
        companies[company] = [employee_id]
    else:
        if employee_id not in companies[company]:
            companies[company] += [employee_id]

for company, employees in sorted(companies.items()):
    print(f"{company}")
    for employee in employees:
        print(f"-- {employee}")

\*9. ForceBook
==
-----------

The force users are struggling to remember which side are the different
forceUsers from, because they switch them too often. So you are tasked
to create a web application to manage their profiles. You should store
an information for every **unique forceUser**, registered in the
application.

You will receive **several input lines** in one of the following
formats:

{forceSide} \| {forceUser}

{forceUser} -\> {forceSide}

The **forceUser and forceSide** are strings, containing any character.

If you receive **forceSide \| forceUser**, you should **check if such
forceUser already exists**, and **if not**, **add** him/her to the
corresponding side.

If you receive a **forceUser -\> forceSide**, you should check if there
is such a **forceUser** already and if so, **change his/her side**. If
there is no such **forceUser**, add him/her to the corresponding
forceSide, treating the command **as a new registered forceUser.**  
**Then you should print on the console: "{forceUser} joins the
{forceSide} side!"**

You should end your program when you receive the command
**"Lumpawaroo"**. At that point you should print each force side,
**ordered descending by forceUsers count, than ordered by name**. For
each side print the **forceUsers**, **ordered by name**.

In case there are **no forceUsers in a side**, you **shouldn\`t print**
the side information.

### Input / Constraints

-   The input comes in the form of commands in one of the formats
    specified above.

-   The input ends, when you receive the command **"Lumpawaroo"**.

### Output

-   As output for each forceSide, **ordered descending by forceUsers
    count**, **then by name**, you must print all the forceUsers,
    **ordered by name alphabetically**.

-   The output format is:

> Side: {forceSide}, Members: {forceUsers.Count}

! {forceUser}

! {forceUser}

! {forceUser}

-   In case there are **NO** **forceUsers**, don\`t print this side.

### Examples

<table>
<thead>
<tr class="header">
<th><strong>Input</strong></th>
<th><strong>Output</strong></th>
<th><strong>Comments</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">

<td><p><strong>Light | Gosho</strong><br><strong>Dark | Pesho</strong><br><strong>Lumpawaroo</strong></p></td>

<td><p><strong>Side: Dark, Members: 1</strong></p>
<p><strong>! Pesho</strong></p>
<p><strong>Side: Light, Members: 1</strong></p>
<p><strong>! Gosho</strong></p></td>
<td><strong>We register Gosho in the Light side and Pesho in the Dark side. After receiving "Lumpawaroo" we print both sides, ordered by membersCount and then by name.</strong></td>
</tr>
<tr class="even">

<td><p><strong>Lighter | Royal</strong><br><strong>Darker | DCay</strong><br><strong>Ivan Ivanov -&gt; Lighter</strong><br><strong>DCay -&gt; Lighter</strong><br><strong>Lumpawaroo</strong></p></td>

<td><p><strong>Ivan Ivanov joins the Lighter side!</strong></p>
<p><strong>DCay joins the Lighter side!</strong></p>
<p><strong>Side: Lighter, Members: 3</strong></p>
<p><strong>! DCay</strong></p>
<p><strong>! Ivan Ivanov</strong></p>
<p><strong>! Royal</strong></p></td>
<td><p><strong>Although Ivan Ivanov doesn`t have profile, we register him and add him to the Lighter side.</strong></p>
<p><strong>We remove DCay from Darker side and add him to Lighter side.</strong></p>
<p><strong>We print only Lighter side because Darker side has no members.</strong></p></td>
</tr>
</tbody>
</table>

\*10. SoftUni Exam Results
==
----------------------

Judge statistics on the last Programing Fundamentals exam was not
working correctly, so you have the task to take all the submissions and
analyze them properly. You should collect all the submissions and print
the final results and statistics about each language that the
participants submitted their solutions in.

You will be receiving lines in the following format:
**"{username}-{language}-{points}" until you receive "exam finished"**.
**You should store each username and his submissions and points.  
You can receive a command to ban a user for cheating in the following
format: "{username}-banned".** In that case, you should **remove** the
user from the contest, but **preserve his submissions in the total count
of submissions for each language**.

**After receiving "exam finished" print each of the participants,
ordered descending by their max points, then by username, in the
following format:**

Results:

{username} \| {points}

…

**After that print each language, used in the exam, ordered descending
by total submission count and then by language name, in the following
format:**

Submissions:

{language} – {submissionsCount}

…

### Input / Constraints

Until you receive "exam finished" you will be receiving participant
submissions in the following format:
**"{username}-{language}-{points}"**.

You can receive a ban command -\> **"{username}-banned"**

The points of the participant will always be a **valid integer in the
range \[0-100\];**

### Output

-   Print the exam results for each participant, ordered descending by
    max points and then by username, in the following format:

Results:

{username} \| {points}

…

-   **After that print each language, ordered descending by total
    submissions and then by language name, in the following format:**

Submissions:

{language} – {submissionsCount}

…

-   Allowed working **time** / **memory**: **100ms** / **16MB**.

### Examples

<table>
<thead>
<tr class="header">
<th><strong>Input</strong></th>
<th><strong>Output</strong></th>
<th><strong>Comment</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">

<td><p>Pesho-Java-84<br>Gosho-C#-84<br>Gosho-C#-70<br>Kiro-C#-94<br>exam finished</p></td>

<td><p>Results:</p>
<p>Kiro | 94</p>
<p>Gosho | 84</p>
<p>Pesho | 84</p>
<p>Submissions:</p>
<p>C# - 3</p>
<p>Java - 1</p></td>
<td><p>We order the participant descending by max points and then by name, printing only the username and the max points.</p>
<p>After that we print each language along with the count of submissions, ordered descending by submissions count, and then by language name.</p></td>
</tr>
<tr class="even">

<td><p>Pesho-Java-91<br>Gosho-C#-84<br>Kiro-Java-90<br>Kiro-C#-50<br>Kiro-banned<br>exam finished</p></td>

<td><p>Results:</p>
<p>Pesho | 91</p>
<p>Gosho | 84</p>
<p>Submissions:</p>
<p>C# - 2</p>
<p>Java - 2</p></td>
<td><p>Kiro is banned so he is removed from the contest, but he`s submissions are still preserved in the languages submissions count.</p>
<p>So althou there are only 2 participants in the results, there are 4 submissions in total.</p></td>
</tr>
</tbody>
</table>